-- Drop existing quoted tables if they exist
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE "ORDER" CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE "USER" CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE "BOOK" CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE "AUTHOR" CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE "IMAGE" CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

-- Recreate everything using unquoted uppercase names
CREATE TABLE IMAGE
(
  ID         VARCHAR2(40) PRIMARY KEY,
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  NAME       VARCHAR2(255)                                      NOT NULL,
  PATH       VARCHAR2(255)                                      NOT NULL
);

CREATE TABLE AUTHOR
(
  ID         VARCHAR2(40) PRIMARY KEY,
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  FIRST_NAME VARCHAR2(255)                                      NOT NULL,
  LAST_NAME  VARCHAR2(255)                                      NOT NULL,
  AGE        NUMBER                                             NOT NULL
);

CREATE TABLE BOOK
(
  ID          VARCHAR2(40) PRIMARY KEY,
  CREATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  TITLE       VARCHAR2(255)                                      NOT NULL,
  DESCRIPTION CLOB,
  GENRE       VARCHAR2(100)                                      NOT NULL,
  YEAR        NUMBER                                             NOT NULL,
  IMAGE_ID    VARCHAR2(40) UNIQUE,
  AUTHOR_ID   VARCHAR2(40),
  CONSTRAINT FK_BOOK_IMAGE FOREIGN KEY (IMAGE_ID) REFERENCES IMAGE (ID) ON DELETE SET NULL,
  CONSTRAINT FK_BOOK_AUTHOR FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR (ID) ON DELETE SET NULL
);

CREATE TABLE "USER"
(
  ID         VARCHAR2(40) PRIMARY KEY,
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  EMAIL      VARCHAR2(255) UNIQUE                               NOT NULL,
  PASSWORD   VARCHAR2(255)                                      NOT NULL,
  ROLE       VARCHAR2(20)             DEFAULT 'USER'            NOT NULL
);

CREATE TABLE "ORDER"
(
  ID          VARCHAR2(40) PRIMARY KEY,
  CREATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_AT  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  NAME        VARCHAR2(255)                                      NOT NULL,
  BORROW_DATE TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  RETURN_DATE TIMESTAMP WITH TIME ZONE,
  STATUS      VARCHAR2(20)             DEFAULT 'ACTIVE'          NOT NULL
    CHECK (STATUS IN ('ACTIVE', 'RETURNED', 'CANCELLED')),
  USER_ID     VARCHAR2(40),
  BOOK_ID     VARCHAR2(40),
  CONSTRAINT FK_ORDER_USER FOREIGN KEY (USER_ID) REFERENCES "USER" (ID) ON DELETE SET NULL,
  CONSTRAINT FK_ORDER_BOOK FOREIGN KEY (BOOK_ID) REFERENCES BOOK (ID) ON DELETE SET NULL
);
